<% if(themeUsesCoffee) {%>
/*
 * This file will contain autogenerated JS from Coffee files
 * Don't Edit it !
 */

<% }
else { %>
/* Drop your main Drupal Scripts here */

(function ($) {

  Drupal.behaviors.<%= themeName %> = {
    attach: function (context, settings) {
      /* do something awesome */
    }
  };

})(jQuery);

<% } %>
